apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keti-gpu-metric-collector
  namespace: gpu
spec:
  selector:
    matchLabels:
      name: gpu-metric-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gpu-metric-collector
    spec:
      serviceAccountName: gpu-metric-collector
      imagePullSecrets: 
      - name: regcred
      restartPolicy: Always
      containers:
      - name: gpu-metric-collector
        image: ketidevit2/keti-gpu-metric-collector:v1.4
        imagePullPolicy: Always
        volumeMounts:
            - name: cpuinfo
              mountPath: /proc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEBUGG_LEVEL
          value: "LEVEL1"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
        - name: cpuinfo
          hostPath:
            path: /proc
