apiVersion: apps/v1
kind: Deployment
metadata:
  name: keti-gpu-metric-collector
  namespace: gpu
spec:
  selector:
    matchLabels:
      name: gpu-metric-collector
  replicas: 4
  template:
    metadata:
      labels:
        name: gpu-metric-collector
    spec:
      serviceAccountName: gpu-metric-collector
      imagePullSecrets: 
      - name: regcred
      restartPolicy: Always
      containers:
      - name: gpu-metric-collector
        image: ketidevit2/keti-gpu-metric-collector:v1.21
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEBUGG_LEVEL
          value: "LEVEL3"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
